name: DevOps Evolution CI-CD Pipeline

on:
  push:
    branches: [hardcode]

# CRUCIAL FOR OIDC: Allows the runner to request secure identity tokens from AWS
permissions:
  id-token: write
  contents: read

jobs:
  terraform-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Clone the repository code
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::955030484164:role/Terraform-user
          aws-region: ap-south-2
          role-session-name: terraform-session

     #install terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      # 3. Terraform Init
      - name: Terraform Init
        run: terraform init  

      # 4. Terraform Plan
      - name: Terraform Plan  
        run:  terraform plan -out=tfplan

      # 5. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan


