---
name: DevOps Evolution 2026 Pipeline

on:
  push:
    branches:
      - main
      - hardcode
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose your Infrastructure Operation'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  #=====================================
  # STAGE 1: THE PLAN & VALIDATION LOOP
  #======================================

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkouy repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE_ARN}}
          aws-region: ap-south-2
          role-session-name: terraform-plan-session

      - name: Install Terraform Engine
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
      
      - name: Initialize Terraform
        run: terraform init

      # EVALUATES WHETHER TO GENERATE A DEPLOYMENT PLAN OR A DESTRUCTION PLAN
      - name: Generate Spec Plan
        id: plan_step
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "Generating destruction manifest blueprint..."
            terraform plan -destroy -out=tfplan
          else
            echo "Generating standard deployment manifest blueprint..."
            terraform plan -out=tfplan
          fi

      - name: Generate Spec plan
        run: terraform plan -out=tfplan

            # ARCHITECTURAL STEP: Upload the plan file securely to GitHub's storage memory  
      - name: Save Execution Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-tfplan
          path: tfplan
          retention-days: 1
  # ==========================================
  # STAGE 2: THE CONTROLLED DEPLOYMENT GATE
  # ==========================================
  terraform-apply:
    runs-on: ubuntu-latest
    # CRUCIAL: Do not run the apply unless the plan job finishes completely green!
    needs: terraform-plan
        # Ties this specific job to an explicit environment gate inside GitHub
    environment: Prod
    
    steps:
      - name: Checkout Code repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{secrets.AWS_IAM_ROLE_ARN}}
          aws-region: ap-south-2
          role-session-name: terraform-apply-session
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
          
      - name: Initialize Terraform
        run: terraform init

      # Download the exact, validated plan binary artifact generated in Job 1
      
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-tfplan

      - name: Execute Controlled Deployment
        run: terraform apply -auto-approve tfplan
      
        # DYNAMIC SUMMARY GENERATION STEP
      - name: Execute Controlled Deployment or Destruction
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "🚨 UI Choice detected: Executing verified safe destruction lifecycle..."
            terraform apply -auto-approve tfplan
          else
            echo "🚀 UI Choice detected: Executing verified standard deployment lifecycle..."
            terraform apply -auto-approve tfplan
          fi


      - name: Generate Live Summary Dashboard
        if: github.event.inputs.action != 'destroy'
        run: |
          # Fetch tracking strings from your outputs configuration layer
          PUBLIC_IP=$(terraform output -raw prod_sever_ip)
          SERVER_URL=$(terraform output -raw prod_web_server_url)
          SSH_CMD=$(terraform output -raw prod_ssh_command)
          
          # Stream clean Markdown text blocks into GitHub's built-in summary page parameter
          echo "### 🚀 DEPLOYMENT COMPLETED SUCCESSFULLY" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "* **Public IP Address:** \`$PUBLIC_IP\`" >> $GITHUB_STEP_SUMMARY
          echo "* **Live Application Link:** [Click to Open Web App]($SERVER_URL)" >> $GITHUB_STEP_SUMMARY
          echo "* **Secure Connection Terminal String:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "$SSH_CMD" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY





