name: DevOps Evolution CI-CD Pipeline

on:
    push:
      branches:
        - hardcode
    workflow_dispatch:

# CRUCIAL FOR OIDC: Allows the runner to request secure identity tokens from AWS
permissions:
  id-token: write
  contents: read

jobs:
  terraform-pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-south-2"
    
    steps:
      # 1. Clone the repository code
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN}} 

     #install terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # 3. Terraform Init
      - name: Terraform Init
        run: terraform init  

      # 4. Terraform Plan
      - name: Terraform Plan  
        run:  terraform plan -out=tfplan -input=false

      # 5. Terraform Apply
      - name: Terraform destroy
        run: terraform destroy -auto-approve tfplan


